package lay3r:avs@0.3.0;

interface types {
  /// serialized json, avs wasi and lay3r contract must agree on the types
  /// the runner is agnostic to the data format
  type serialized-json = list<u8>;

  record task-queue-input {
    // this does *not* match the contract. TBD
    timestamp: u64,
    request: serialized-json,
  }

  type error = string;

  type output = result<serialized-json, error>;
}

world task-queue {
  import wasi:io/poll@0.2.0;
  import wasi:clocks/monotonic-clock@0.2.0;
  import wasi:io/error@0.2.0;
  import wasi:io/streams@0.2.0;
  import wasi:http/types@0.2.0;
  import wasi:http/outgoing-handler@0.2.0;
  import types;
  use types.{task-queue-input, output};

  export run-task: func(request: task-queue-input) -> output;
}
world cron-job {
  import wasi:io/poll@0.2.0;
  import wasi:clocks/monotonic-clock@0.2.0;
  import wasi:io/error@0.2.0;
  import wasi:io/streams@0.2.0;
  import wasi:http/types@0.2.0;
  import wasi:http/outgoing-handler@0.2.0;
  import types;
  use types.{output};

  export run-cron: func() -> output;
}
